blueprint:
  # https://www.home-assistant.io/docs/blueprint/schema/
  # https://www.home-assistant.io/docs/automation/basics/
  name: Pixelix - Send sensor data to Pixelix device
  description: |
    # Pixelix Automation Blueprint

    This blueprint allows you to monitor multiple sensors in realtime on Pixelix.
    You can choose between the JustText, IconText or IconTextLamp plugin to display the sensor data.
  domain: automation
  author: Pixelix & Friends <https://github.com/BlueAndi/Pixelix>
  source_url: https://www.blue-andi.de/vscp/pixelix_send_sensor_data.yaml
  homeassistant:
    min_version: 2024.10.0
  # https://www.home-assistant.io/docs/blueprint/selectors/
  input:
    section_general:
      name: General Section
      description: General configuration independed of using REST or MQTT API.
      input:
        plugin_type:
          name: Plugin Type
          description: The type of the plugin.
          selector:
            select:
              options:
                - label: JustText Plugin
                  value: justtext
                - label: IconText Plugin
                  value: icontext
                - label: IconTextLamp Plugin
                  value: icontextlamp
        uid:
          name: Plugin UID
          description: The plugin UID of the plugin instance. See display page in the Pixelix web interface.
          selector:
            number:
              min: 0
              max: 65535
              mode: box
        sensors:
          name: Sensors
          description: The sensors to monitor in realtime.
          selector:
            entity:
              multiple: true
        icon_selector:
          name: Icon Selector
          description: 'Optional: Keep current icon or change it. Only used by IconText and IconTextLamp plugins.'
          default: keep
          selector:
            select:
              options:
                - label: Keep current icon
                  value: keep
                - label: Change icon
                  value: change
        icon_file_id:
          name: Icon File ID
          description: |
            The file ID of the icon to display.
            See Pixelix icons web page for the available icons.
            255 means no icon.
            A icon is only supported by IconText and IconTextLamp plugins.
          default: 255
          selector:
            text:
        user_triggers:
          name: User Triggers
          description: Additional triggers defined by the user.
          default:
          selector:
              trigger:
        user_conditions:
          name: User Conditions
          description: User defined conditions for the automation.
          default: []
          selector:
            condition:
        horizontal_alignment:
          name: Horizontal Alignment
          description: The horizontal alignment of the text.
          default: default
          selector:
            select:
              options:
                - label: Default
                  value: default
                - label: Left
                  value: hl
                - label: Center
                  value: hc
                - label: Right
                  value: hr
        vertical_alignment:
          name: Vertical Alignment
          description: The vertical alignment of the text.
          default: default
          selector:
            select:
              options:
                - label: Default
                  value: default
                - label: Top
                  value: vt
                - label: Center
                  value: vc
                - label: Bottom
                  value: vb
        prefix_text:
          name: Prefix Text
          description: 'Optional: The text to display before the sensor value(s).'
          default: ''
          selector:
            text:
        suffix_text:
          name: Suffix Text
          description: 'Optional: The text to display after the sensor value(s).'
          default: ''
          selector:
            text:
        sensor_labels:
          name: Sensor labels
          description: 'Optional: The labels of the sensors. Please use \"-\" before each entry and add as many entries as the number of your selected sensors. Each line should contain one entry.'
          default: []
          selector:
            object:
    section_color:
      name: Color Section
      description: Configuration of the text color.
      input:
        color_selector:
          name: Color Selector
          description: The color selector of the text.
          default: default
          selector:
            select:
              options:
                - label: Default
                  value: default
                - label: Solid Color
                  value: solid_color
                - label: Linear Gradient Color
                  value: linear_gradient_color
        solid_color:
          name: Color of the solid color brush
          description: The solid color of the text.
          default: "#FFFFFF"
          selector:
            text:
                type: color
        linear_gradient_color1:
          name: Color 1 of the linear gradient brush
          description: The first color of the linear gradient of the text.
          default: "#FF0000"
          selector:
            text:
              type: color
        linear_gradient_color2:
          name: Color 2 of the linear gradient brush
          description: The second color of the linear gradient of the text.
          default: "#0000FF"
          selector:
            text:
              type: color
        linear_gradient_direction:
          name: Gradient Direction
          description: 'Optional: The gradient direction of the text color.'
          default: vertical
          selector:
            select:
              options:
                - label: Vertical (Top to bottom)
                  value: vertical
                - label: Horizontal (Left to right)
                  value: horizontal
        linear_gradient_offset:
          name: Gradient Offset
          description: 'Optional: The offset of the gradient in pixels.'
          default: 0
          selector:
            number:
              min: 0
              max: 32767
              mode: box
        linear_gradient_length:
          name: Gradient Length
          description: 'Optional: The length of the gradient in pixels.'
          default: 32
          selector:
            number:
              min: 0
              max: 65535
              mode: box
    section_protocol:
      name: Protocol Section
      description: |
        # Protocol specific configuration.

        ## MQTT API

        For the communication to Pixelix via MQTT API, you need to install the MQTT integration in Home Assistant and
        configure it to connect to your MQTT broker.

        Enable MQTT in Pixelix via the settings web page. Pixelix uses the MQTT automatic discovery feature.

        ## REST API

        For the REST API add the following REST command to your configuration.yaml in Home Assistant.
        It will be called by the automation blueprint.

        ```yaml
          rest_command:
            pixelix_plugin_command:
              url: "http://{{ hostname }}{{ endpoint }}?{{ url_parameter }}"
              method: POST
        ```
      input:
        protocol:
          name: Communication Protocol
          description: The protocol to use for communication.
          default: mqtt
          selector:
            select:
              options:
                - label: MQTT API
                  value: mqtt
                - label: REST API
                  value: rest
        pixelix_device:
          name: MQTT Pixelix device
          description: |
            The Pixelix device to use for MQTT communication.
            Only used by MQTT API protocol selection.
          default:
          selector:
            device:
              integration: mqtt
              manufacturer: BlueAndi & Friends
              model: Pixelix
        pixelix_hostname:
          name: Pixelix Hostname
          description: |
            Enter the hostname (e.g. pixelix-FFFFFFFF or 192.168.178.110) of the Pixelix device.
            Only used by REST API protocol selection.
          default: ""
          selector:
            text:

variables:
  var_plugin_type: !input plugin_type
  var_uid: !input uid
  var_sensors: !input sensors
  var_icon_selector: !input icon_selector
  var_icon_file_id: !input icon_file_id
  var_horizontal_alignment: !input horizontal_alignment
  var_vertical_alignment: !input vertical_alignment
  var_color_selector: !input color_selector
  var_prefix_text: !input prefix_text
  var_suffix_text: !input suffix_text
  var_sensor_labels: !input sensor_labels
  var_protocol: !input protocol
  var_solid_color: !input solid_color
  var_linear_gradient_color1: !input linear_gradient_color1
  var_linear_gradient_color2: !input linear_gradient_color2
  var_linear_gradient_direction: !input linear_gradient_direction
  var_linear_gradient_offset: !input linear_gradient_offset
  var_linear_gradient_length: !input linear_gradient_length
  var_device: !input pixelix_device
  var_hostname: !input pixelix_hostname
  var_alignment: >-
    {% set horizontal_alignment = var_horizontal_alignment %}
    {% set vertical_alignment = var_vertical_alignment %}
    {% set alignment = 'default' %}
    {% if horizontal_alignment != 'default' %}
      {% set alignment = horizontal_alignment %}
    {% endif %}
    {% if vertical_alignment != 'default' %}
      {% if alignment != '' %}
        {% set alignment = alignment + vertical_alignment %}
      {% else %}
        {% set alignment = vertical_alignment %}
      {% endif %}
    {% endif %}
    {{ alignment }}
  var_color_tag: >-
    {% set color_selector = var_color_selector %}
    {% set solid_color = var_solid_color %}
    {% set linear_gradient_color1 = var_linear_gradient_color1 %}
    {% set linear_gradient_color2 = var_linear_gradient_color2 %}
    {% set linear_gradient_direction = var_linear_gradient_direction %}
    {% set linear_gradient_offset = var_linear_gradient_offset %}
    {% set linear_gradient_length = var_linear_gradient_length %}
    {% set color_tag = 'default' %}
    {% if color_selector == 'solid_color' %}
      {% set color_tag = solid_color %}
    {% elif color_selector == 'linear_gradient_color' %}
      {% if linear_gradient_direction == 'vertical' %}
        {% set color_tag = 'lgv ' + linear_gradient_color1 + ',' + linear_gradient_color2 + ',' + linear_gradient_offset|string + ',' + linear_gradient_length|string %}
      {% else %}
        {% set color_tag = 'lgh ' + linear_gradient_color1 + ',' + linear_gradient_color2 + ',' + linear_gradient_offset|string + ',' + linear_gradient_length|string %}
      {% endif %}
    {% endif %}
    {{ color_tag }}
  var_plugin_topic: >-
    {% set plugin_type = var_plugin_type %}
    {% set plugin_topic = '' %}
    {% if plugin_type == 'justtext' %}
      {% set plugin_topic = 'text' %}
    {% else %}
      {% set plugin_topic = 'iconText' %}
    {% endif %}
    {{ plugin_topic }}
  var_text: >-
    {% set sensors = var_sensors %}
    {% set prefix_text = var_prefix_text %}
    {% set suffix_text = var_suffix_text %}
    {% set sensor_labels = var_sensor_labels %}
    {% set alignment = var_alignment %}
    {% set color_tag = var_color_tag %}
    {% set ns = namespace(texts = [], tags = []) %}
    {% if alignment != 'default' %}
      {% set ns.tags = ns.tags + [alignment] %}
    {% endif %}
    {% if color_tag != 'default' %}
      {% set ns.tags = ns.tags + [color_tag] %}
    {% endif %}
    {% if prefix_text != '' %}
      {% set ns.texts = ns.texts + [prefix_text] %}
    {% endif %}
    {% for sensor in sensors %}
      {% set state = states(sensor) %}
      {% set unit = state_attr(sensor, 'unit_of_measurement') %}
      {% set label = '' %}
      {% if ((sensor_labels is defined) and (loop.index <= sensor_labels|length)) %}
        {% set label = sensor_labels[loop.index - 1] %}
      {% endif %}
      {% if (state != 'unknown') and (state != 'unavailable') %}
        {% if label != '' %}
          {% set state = label + ':' + state %}
        {% endif %}
        {% if unit != None %}
          {% set ns.texts = ns.texts + [state + unit] %}
        {% else %}
          {% set ns.texts = ns.texts + [state] %}
        {% endif %}
      {% endif %}
    {% endfor %}
    {% if suffix_text != '' %}
      {% set ns.texts = ns.texts + [suffix_text] %}
    {% endif %}
    {{ ns.tags | map('regex_replace', '^(.*)$', '{\\1}') | join() }}{{ ns.texts | join(' ') }}
  var_mqtt_payload: >-
    {% set icon_selector = var_icon_selector %}
    {% set icon_file_id = var_icon_file_id %}
    {% set text = var_text %}
    {% if (icon_selector == 'change') and ((var_plugin_type == 'icontext') or (var_plugin_type == 'icontextlamp')) %}
      {"iconFileId": {{ icon_file_id }}, "text": "{{ text }}"}
    {% else %}
      {"text": "{{ text }}"}
    {% endif %}
  var_rest_url_parameter: >-
    {% set icon_selector = var_icon_selector %}
    {% set icon_file_id = var_icon_file_id %}
    {% set text = var_text %}
    {% if (icon_selector == 'change') and ((var_plugin_type == 'icontext') or (var_plugin_type == 'icontextlamp')) %}
      {{ ("iconFileId=" + icon_file_id + "&text=" + text) | urlencode() }}
    {% else %}
      {{ ("text=" + text) | urlencode() }}
    {% endif %}

# https://www.home-assistant.io/docs/automation/trigger/
triggers:
  - trigger: state
    entity_id: !input sensors

  - trigger: homeassistant
    event: start
    id: update

  - trigger: event
    event_type: automation_reloaded
    id: update

  # Merge user defined triggers
  - triggers: !input user_triggers

# https://www.home-assistant.io/docs/automation/condition/
conditions: !input user_conditions

# https://www.home-assistant.io/docs/automation/action/
actions:
  - choose:
    # Use MQTT API
    - conditions:
      - condition: template
        value_template: "{{ var_protocol == 'mqtt' }}"
      - condition: template
        value_template: "{{ var_device and var_hostname == '' }}"
      sequence:
        - action: mqtt.publish
          data:
            topic: "{{ device_attr(var_device, 'name') }}/display/uid/{{ var_uid }}/{{ var_plugin_topic }}/set"
            payload: "{{ var_mqtt_payload }}"

    # Use REST API
    - conditions:
      - condition: template
        value_template: "{{ var_protocol == 'rest' }}"
      - condition: template
        value_template: "{{ var_device is none and var_hostname != '' }}"
      sequence:
        - action: rest_command.pixelix_plugin_command
          data:
            hostname: "{{ var_hostname }}"
            endpoint: "/rest/api/v1/display/uid/{{ var_uid }}/{{ var_plugin_topic }}"
            url_parameter: "{{ var_rest_url_parameter }}"

    # Default
    default:
      - service: persistent_notification.create
        data:
          title: "Pixelix Automation Notification"
          message: "Error: Could not send text to Pixelix device. Please check your configuration."

# https://www.home-assistant.io/docs/automation/modes/
mode: single
